name: srumcontacts
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_launcher_icons: ^0.6.1
  shared_preferences: ^0.4.3
  json_annotation: ^2.0.0
  path_provider: ^0.4.1
  url_launcher: ^4.0.1
  image_picker: ^0.4.10
  sqflite: ^0.12.2+1
  http: ^0.12.0
  intl: ^0.15.7

flutter:


  uses-material-design: true

